
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terra_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8081